version: "3.7"

services:
  postgres:
    image: postgres:latest
    container_name: ya41-56-pg
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  adminer:
    image: adminer
    container_name: ya41-56-adminer
    restart: always
    ports:
      - "9080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
